version: '3'
services:
  web:
    restart: always
    build: ./starwars
    ports:
      - "8000:8000"
    links:
      - redis:redis
    command: 
      - ./run.sh

  redis:
    restart: always
    image: redis:4.0.6